### ISSUE TITLE
API sort by distance

### ISSUE THREAD

**Issue by krose098** [dlakaplan/pulsarsurveyscraper#7]
For coordinates with multiple PSR matches, would it possible to make the API default to return the matches sorted by distance from the coordinates. This is the case for the webpage return and seems more practical than arranging the API return alphabetically. 
Cheers

**Comment by dlakaplan** [comment]
To be clear, this is an issue with https://github.com/dlakaplan/pulsarsurveyscraper_server (the server), not the underlying scraper code.

In any case, the (re)sorting was done by the web front-end.  I was actually feeding data sorted by distance and it was making it alphabetical so that it always had the same hash (to aid in caching).  I think that's not a big issue in this case so I turned it off.  Let me know if that works.

**Comment by krose098** [comment]
Sorry for the confusion between the code and the server.
Yes this has fixed the issue. Thank you :)
